service: phonebook

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam: 
    role: 
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

plugins:
  - serverless-offline

functions:
  list:
    handler: functions/getbook.hello
    events: 
      - http:
          method: get
          path: person
          cors: true

  getone:
    handler: functions/getone.getone
    events: 
      - http:
          method: get
          path: person/{key}
          cors: true

  getonefrombase:
    handler: functions/getonefrombase.getonefrombase
    events: 
      - http:
          method: get
          path: person/getfrombase
          cors: true

  add:
    handler: functions/addperson.add
    events:
      - http:
          method: post
          path: person
          cors: true

  adtobase:
    handler: functions/addtobase.add
    events:
      - http:
          method: post
          path: person/base
          cors: true

  update:
    handler: functions/update.update
    events: 
      - http:
          method: put
          path: person
          cors: true

  delete:
    handler: functions/delete.delete
    events:
      - http:
          method: delete
          path: person/{key}
          cors: true

resources: 
  Resources:
    Database:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: guid
            AttributeType: S

          -
            AttributeName: name
            AttributeType: S

        KeySchema:
          -
            AttributeName: guid
            KeyType: HASH

          -
            AttributeName: name
            KeyType: RANGE
        
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        
        TableName: "phonebook"